custom login

diff --git a/0x0F-load_balancer/login_server b/0x0F-load_balancer/login_server
--- a/0x0F-load_balancer/login_server
+++ b/0x0F-load_balancer/login_server
@@ -1,4 +1,15 @@
 #!/usr/bin/env bash
 # uses ssh to connect to your server using the private key
 
-ssh -i ~/.ssh/school ubuntu@100.26.216.42
+if [ "$#" -ne 1 ];
+then
+	echo "Usage: $0 server_ip"
+	exit 1
+fi
+
+ssh -i ~/.ssh/school ubuntu@"$1"
+
+if [ $? -ne 0 ]; then
+	echo "Failed to connect to the server."
+	exit 1
+fi
